name: sample_mangakakalot_db
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  html: ^0.15.0
  http: ^0.13.3
  pretty_json: ^2.0.0
  path_provider: ^2.0.1
  cached_network_image: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  marquee: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  hive_generator: ^1.1.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

#  assets:
#    - assets/
#    - assets/res/

